version: "3"
networks:
  dinky_net:
    external: true
services:
  dinky:
    container_name: dinky
    restart: always
    image: localhost:5000/dinky/dinky-test:flink
    environment:
      - DB_ACTIVE=mysql
      - MYSQL_ADDR=mysql:3306
      - MYSQL_DATABASE=dinky
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=dinky
    volumes:
      - ./mysql-connector-java-8.0.30.jar:/opt/dinky/lib/mysql-connector-java-8.0.30.jar
      - ./javax.ws.rs-api-2.1.1.jar:/opt/dinky/lib/javax.ws.rs-api-2.1.1.jar
      - ../flink/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/dinky/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
      - ../flink/conf/log4j-console.properties:/opt/flink/conf/log4j-console.properties
      - ../hadoop:/opt/flink/conf
      - ./jars:/dinky
    networks:
      - dinky_net
